name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull docker image
      run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/altium-migrator:latest

    - name: Run docker container
      run: >
          docker run altium-migrator:latest -p 5432:5432
          --spring.profiles.active=prod
          --spring.datasource.url=${{ secrets.ALTIUM_DB_DATASOURCE }}
          --spring.datasource.username=${{ secrets.ALTIUM_DB_USERNAME }}
          --spring.datasource.password=${{ secrets.ALTIUM_DB_PASSWORD }}